-- Initial Schema for Supabase (PostgreSQL)

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price REAL NOT NULL,
  image_url TEXT,
  description TEXT,
  active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  total_amount REAL NOT NULL,
  status TEXT DEFAULT 'ממתין לאימות',
  delivery_method TEXT,
  address TEXT,
  receipt_preference TEXT,
  notes TEXT,
  is_archived BOOLEAN DEFAULT FALSE,
  archive_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  price REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS bundles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  capacity INTEGER NOT NULL,
  discount_percent INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_date TEXT NOT NULL,
  supplier TEXT NOT NULL,
  category TEXT NOT NULL,
  amount REAL NOT NULL,
  receipt_image_url TEXT,
  is_archived BOOLEAN DEFAULT FALSE,
  archive_name TEXT
);

CREATE TABLE IF NOT EXISTS discount_tiers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  min_qty INTEGER NOT NULL,
  discount_percent INTEGER NOT NULL
);

-- Default Settings
INSERT INTO settings (key, value) VALUES 
('sumit_company_id', '2422708697'),
('sumit_api_key', '1hvvEIVHWUz3vDAbIleFFRkBGMV1njPYFDHJ4kxChH5a3ijPhD'),
('ypay_token', ''),
('store_name', 'Roll & Bake'),
('store_info', 'כשר חלבי למהדרין | כל המוצרים בכשרות בד"ץ'),
('store_subtitle', 'סינבונים מושחתים בעבודת יד'),
('logo_url', '/logo-transparent.png')
ON CONFLICT (key) DO NOTHING;

-- Default Products
INSERT INTO products (name, price, image_url, description) VALUES 
('סינבון קינמון קלאסי', 20, '/סינבון בטעם קינמון קלאסי.png', 'בצק שמרים רך ונימוח במילוי קינמון עשיר.'),
('סינבון שוקולד עשיר', 22, '/סינבון בטעם שוקולד עשיר.png', 'הקלאסיקה המוכרת בגרסה שוקולדית.'),
('סינבון פקאן וקרמל', 24, '/סינבון בטעם פקאן קרמל.png', 'שילוב מעודן של מתוק ומלוח.')
ON CONFLICT DO NOTHING;
